<?php

/**
 * Implements hook_install().
 */
function nrw_base_theme_install() {
  // Set default settings.
  \Drupal::configFactory()->getEditable('nrw_base_theme.settings')
    ->set('fluid_container', '1')
    ->set('breadcrumb_home', '1')
    ->set('breadcrumb_title', '0')
    ->save();
  // Force config installation as the profile installer refuses this step otherwise.
  \Drupal::service('degov_config.updater')->configPartialImport('nrw_base_theme', 'optional', 'theme');
}